import { generateKey } from 'openpgp';
import { pbkdf2 } from 'pbkdf2';

import { UserKeys } from '../types/UserKeys';

export const asyncPBKDF2 = async (str: string, salt: string): Promise<string> =>
  new Promise((resolve, reject) => {
    pbkdf2(str, salt, 100000, 64, (err, derivedKey) => {
      if (err) {
        reject(err);
      } else {
        resolve(derivedKey.toString('hex'));
      }
    });
  });

export const newKeyPair = async (
  email: string,
  passphrase: string,
  name?: string
): Promise<UserKeys> => {
  if (passphrase.length < 8) {
    throw new Error('Passphrase must be at least 8 character long');
  }

  return generateKey({
    type: 'ecc',
    curve: 'p521',
    userIDs: [
      { email, comment: 'Generated by OpenPGP.js in Task Stash', name },
    ],
    passphrase,
    format: 'armored',
  });
};
