import { generateKey,type SerializedKeyPair } from 'openpgp';

export const newKey = async (email: string, passphrase: string, name?: string):Promise<SerializedKeyPair<string> & {
  revocationCertificate: string;
}> => {
  if (passphrase.length < 8) {
    throw new Error('Passphrase must be at least 8 character long');
  }

  return await generateKey({
    type: 'ecc',
    curve: 'p521',
    userIDs: [
      { email, comment: 'Generated by OpenPGP.js in Task Stash', name },
    ],
    passphrase,
    format: 'armored',
  });
};
